version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "ch.qos.logback:logback-classic"
      # Ignore version 1.4 and higher as they target Java 11
      # See https://logback.qos.ch/dependencies.html
      versions: ["[1.4,)"]